### ISSUE TITLE
(minor) Workspace: "Remove filter..." is displayed by default in all filters

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#76] opened 2016-03-16 12:55 UTC
Environment: win7+ie11, win10+edge

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Check any time series and add this timeseries to workspace
5. Click "Open Workspace"

Result:
"Remove filter..." is displayed by default in all filters (see att.)
![28](https://cloud.githubusercontent.com/assets/17844881/13812863/7dac1612-eb8f-11e5-9b80-c36780603539.png)

Expected result:
"Filter by: column name" is displayed by default in all filters

**Comment by ghost** [comment] 2016-03-30 16:52
BCC - 30-Mar-2016 - Fixed in IE 11

Known IE 11 issue as explained here: http://stackoverflow.com/questions/27283887/adding-selected-and-disabled-attributes-to-an-option-tag-in-ie-11

Applied recommended fix.

**Comment by ghost** [comment] 2016-04-05 16:53
BCC - 05-Apr-2016- Fixed in Edge 

Tested in Edge browser running under Windows 10.  Not able to reproduce problem.  Assume problem fixed by earlier IE 11 fix...

**Comment by ghost** [comment] 2016-11-14 22:52
Fixed per 30-Mar and 05-Apr comments

**Closed as completed by ghost** 2016-11-14 22:52 UTC
