### ISSUE TITLE
(minor) Select Date Range: warning message shown for correct dates in some cases

### ISSUE THREAD

**Issue by Stref** [CUAHSI/HISWebClientIssues#50] opened 2015-08-13 10:07 UTC
_Steps to reproduce:_
1. Navigate to http://qa-hiswebclient.azurewebsites.net/
2. Click "Select Date Range" button 
3. set 'from' date = 01/01/2008 
4. set 'to' date using calendar =  09/19/2007 (warning messages has appeared)
5. click 'Close' button
6. click  "Select Date Range" button

_Result:_
Dates are correct, but warning message still shown to the user
![143](https://cloud.githubusercontent.com/assets/13001938/9247502/30cdfbd0-41bc-11e5-9c73-0e92bca59c6c.png)

_Expected result:_
Dates are correct, warning message should be disabled for that case

**Comment by ghost** [comment] 2015-08-18 16:33
BCC - 18-Aug-2015 - Reviewed and reproduced reported issue.

Recommendation: Fix

Proposed fix:  Revised date dialog open logic to include validation of input 'From' and 'To' values, thereby removing any 'error' classes remaining from earlier dialog displays assuming the input date values are correct...

**Comment by ghost** [comment] 2016-03-31 18:15
BCC - 31-Mar-2016 - Already fixed 

Not able to reproduce reported issue - assume fixed by previous development...

**Comment by ghost** [comment] 2016-11-15 00:16
Fixed - per 31-Mar-2016 comments...

**Closed as completed by ghost** 2016-11-15 00:16 UTC
