### ISSUE TITLE
(average) Workspace: time serie created date&time isn't displayed

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#80] opened 2016-03-16 14:23 UTC
Environment: win7+ie11, win10+edge, win7+FF, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Search for any time series
3. Click "Show Search Results"
4. Check any time series and add this timeseries to workspace
5. Click "Open Workspace"
6. Note value in Created column

Result:
Time serie created date&time isn't displayed (see att.)
![33](https://cloud.githubusercontent.com/assets/17844881/13815459/b1eb71b4-eb9b-11e5-97b2-de5b0f479053.png)

Expected result:
Time serie created date&time is displayed

Note: issue actual for authorized and non-authorized users

**Comment by ghost** [comment] 2016-03-29 20:52
BCC - 29-Mar-2016 - Not able to reproduce 

Please see my remarks for the related issue: #81

**Comment by ghost** [comment] 2016-11-14 20:49
Fixed by changes in creation date storage/display logic

**Closed as completed by ghost** 2016-11-14 20:49 UTC
