### ISSUE TITLE
(average) Authorized user: Workspace: incorrect date&time of creating is displayed after re-login

### ISSUE THREAD

**Issue by vladutko** [CUAHSI/HISWebClientIssues#81] opened 2016-03-16 14:30 UTC
Environment: win7+ie11, win10+edge, win7+FF, Mac OS X 10.11 El Capitan + Safari 9.0

Steps to reproduce:
1. Navigate to http://qa-webclient-solr.azurewebsites.net/
2. Sign in with Google account
3. Search for any time series
4. Click "Show Search Results"
5. Check any time series and add this timeseries to workspace
6. Re-login
7. Click "Workspace"
8. Note values in "Created" column

Result:
Incorrect date&time of creating is displayed after re-login (see att.)
![34](https://cloud.githubusercontent.com/assets/17844881/13815726/bd248ff6-eb9c-11e5-9f04-cdeddc4abe6f.png)

Expected result:
Correct date&time of creating is displayed after re-login

**Comment by ghost** [comment] 2016-03-29 19:43
BCC - 29-Mar-2016 - Not able to reproduce 

In my current local build, followed steps to reproduce.
As shown below, Created Dates appeared correctly in Workspace...

![2016-03-29_15-37-48](https://cloud.githubusercontent.com/assets/7917808/14121312/e15dd184-f5c4-11e5-9c7e-64681315335a.png)

**Comment by ghost** [comment] 2016-11-14 20:47
Fixed by changes in creation date storage/display logic

**Closed as completed by ghost** 2016-11-14 20:47 UTC
